import type { TrendData, ActiveSession } from "../types/system";
import type { AuditEvent } from "../types/audit";

function makeTrend(base: number, variance: number): number[] {
  const points: number[] = [];
  let v = base;
  for (let i = 0; i < 30; i++) {
    v = Math.max(2, Math.min(100, v + (Math.random() - 0.5) * variance));
    points.push(+v.toFixed(1));
  }
  return points;
}
export const MOCK_ACTIVITY = [
  {
    time: "10:42",
    user: "林威廷",
    action: "更新",
    target: "使用者 chen.peihua 的角色",
    kind: "success" as const,
  },
  {
    time: "10:18",
    user: "admin",
    action: "上傳",
    target: "服務套件 officeai-2.4.1.sp",
    kind: "success" as const,
  },
  {
    time: "09:53",
    user: "system",
    action: "重啟",
    target: "容器 package-scanner",
    kind: "warning" as const,
  },
  {
    time: "09:42",
    user: "admin",
    action: "登入",
    target: "本地驗證",
    kind: "info" as const,
  },
  {
    time: "08:15",
    user: "林威廷",
    action: "登入",
    target: "LDAP 驗證",
    kind: "info" as const,
  },
  {
    time: "08:02",
    user: "system",
    action: "備份",
    target: "資料庫 every-day-02:00",
    kind: "success" as const,
  },
  {
    time: "昨天",
    user: "陳佩樺",
    action: "檢視",
    target: "系統狀態頁面",
    kind: "info" as const,
  },
  {
    time: "昨天",
    user: "admin",
    action: "修改",
    target: "網卡 eno1 改為靜態 IP",
    kind: "warning" as const,
  },
];

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    time: "2025-11-12 14:23:41",
    actor: "admin",
    actorIp: "10.0.1.12",
    category: "身分治理",
    action: "建立使用者",
    target: "chen.peihua",
    outcome: "success",
    detail: "指派角色：審核員",
  },
  {
    time: "2025-11-12 11:08:55",
    actor: "lin.weiting",
    actorIp: "10.0.1.42",
    category: "身分治理",
    action: "更新角色權限",
    target: "營運主管",
    outcome: "success",
    detail: "新增 system.docker",
  },
  {
    time: "2025-11-12 10:51:02",
    actor: "admin",
    actorIp: "10.0.1.12",
    category: "系統部署",
    action: "安裝服務套件",
    target: "OfficeAI-v2.4.1-20251108.sp",
    outcome: "success",
    detail: "部署目錄 /opt/officeai/packages",
  },
  {
    time: "2025-11-12 09:34:17",
    actor: "lin.weiting",
    actorIp: "10.0.1.42",
    category: "網路設定",
    action: "更新介面 IP",
    target: "eno1",
    outcome: "success",
    detail: "DHCP → 靜態 192.168.10.32",
  },
  {
    time: "2025-11-11 22:18:33",
    actor: "unknown",
    actorIp: "203.0.113.7",
    category: "身分驗證",
    action: "登入失敗",
    target: "admin",
    outcome: "failure",
    detail: "密碼錯誤（連續 3 次）",
  },
  {
    time: "2025-11-11 18:02:09",
    actor: "admin",
    actorIp: "10.0.1.12",
    category: "系統部署",
    action: "回滾服務套件",
    target: "OfficeAI-v2.4.0-rc2.sp",
    outcome: "success",
    detail: "回到 v2.4.0",
  },
  {
    time: "2025-11-11 15:41:28",
    actor: "chen.peihua",
    actorIp: "10.0.1.55",
    category: "身分驗證",
    action: "變更密碼",
    target: "自身",
    outcome: "success",
    detail: "",
  },
  {
    time: "2025-11-11 14:12:50",
    actor: "admin",
    actorIp: "10.0.1.12",
    category: "身分治理",
    action: "停用使用者",
    target: "wang.guest",
    outcome: "success",
    detail: "長期未登入",
  },
  {
    time: "2025-11-11 11:09:04",
    actor: "system",
    actorIp: "127.0.0.1",
    category: "系統部署",
    action: "排程備份",
    target: "/var/backups/officeai",
    outcome: "success",
    detail: "每日 11:00",
  },
  {
    time: "2025-11-11 09:22:18",
    actor: "lin.weiting",
    actorIp: "10.0.1.42",
    category: "網路設定",
    action: "修改 DNS",
    target: "eno1",
    outcome: "success",
    detail: "加入 8.8.4.4",
  },
  {
    time: "2025-11-10 23:55:47",
    actor: "system",
    actorIp: "127.0.0.1",
    category: "系統健康",
    action: "CPU 告警",
    target: "office-ai-api",
    outcome: "warning",
    detail: "5 分鐘平均 87%（閾值 80%）",
  },
  {
    time: "2025-11-10 16:08:12",
    actor: "admin",
    actorIp: "10.0.1.12",
    category: "身分治理",
    action: "建立角色",
    target: "稽核員（自訂）",
    outcome: "success",
    detail: "複製自審核員",
  },
];

export const MOCK_SESSIONS: ActiveSession[] = [
  {
    id: "s1",
    user: "admin",
    displayName: "系統管理員",
    ip: "10.0.1.12",
    device: "Chrome 130 · macOS",
    loginAt: "2025-11-12 08:42",
    lastActivity: "剛剛",
    mfa: true,
    current: true,
  },
  {
    id: "s2",
    user: "admin",
    displayName: "系統管理員",
    ip: "10.0.1.12",
    device: "Safari · iPhone",
    loginAt: "2025-11-12 07:15",
    lastActivity: "12 分鐘前",
    mfa: true,
    current: false,
  },
  {
    id: "s3",
    user: "lin.weiting",
    displayName: "林威廷",
    ip: "10.0.1.42",
    device: "Chrome 130 · Windows",
    loginAt: "2025-11-12 09:01",
    lastActivity: "3 分鐘前",
    mfa: true,
    current: false,
  },
  {
    id: "s4",
    user: "chen.peihua",
    displayName: "陳佩樺",
    ip: "10.0.1.55",
    device: "Firefox 132 · Linux",
    loginAt: "2025-11-12 09:34",
    lastActivity: "剛剛",
    mfa: false,
    current: false,
  },
  {
    id: "s5",
    user: "audit.bot",
    displayName: "稽核機器人",
    ip: "127.0.0.1",
    device: "API · curl/8.4",
    loginAt: "2025-11-12 06:00",
    lastActivity: "30 秒前",
    mfa: false,
    current: false,
  },
];

export const MOCK_TRENDS: TrendData = {
  cpu: makeTrend(32, 14),
  memory: makeTrend(64, 6),
  gpu: makeTrend(78, 10),
};
